const RE_DATA = [
  {
    "image": "assets/images/test.png",
    "amount": 200000,
    "address": "Jenison, MI 49428, SF",
    "bedrooms": 4,
    "bathrooms": 2,
    "area": 1416,
    "garage": 1,
    "description": "Lorem Ipsum is simply",
  },
  {
    "image": "assets/images/7_.png",
    "amount": 180000,
    "address": "Jenison, MI 49428, SF",
    "bedrooms": 4,
    "bathrooms": 2,
    "area": 1416,
    "garage": 1,
    "description": "Lorem Ipsum is simply",
  },
  {
    "image": "assets/images/7_.png",
    "amount": 180000,
    "address": "Jenison, MI 49428, SF",
    "bedrooms": 4,
    "bathrooms": 2,
    "area": 1416,
    "garage": 1,
    "description": "Lorem Ipsum is simply",
  },
  {
    "image": "assets/images/7_.png",
    "amount": 180000,
    "address": "Jenison, MI 49428, SF",
    "bedrooms": 4,
    "bathrooms": 2,
    "area": 1416,
    "garage": 1,
    "description": "Lorem Ipsum is simply",
  },
];
